name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v2
      with:
        node-version: 15
        check-latest: true
    - uses: actions/cache@v2 # [H]
      with:
        path: |
          ${{ github.workspace }}/node_modules
          ${{ github.workspace }}/.next/cache # [I]
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js') }}
        # If source files changed but packages didn't, rebuild from a prior cache. 
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - run: npm install # [E]
    - run: npm run build # [F]
    - uses: stefanzweifel/git-auto-commit-action@v4 # [G]
      with:
        commit_message: Automated publish

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: ${{ secrets.PATH }}

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.PATH }} && pm2 start ecosystem.config.js